allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - "@types/node@22.19.19"
onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
